# Generated by Django 5.2.11 on 2026-09-30 08:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_alter_historicalproduct_image_alter_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='possale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total value given away via manual line-price overrides on this sale.', max_digits=10),
        ),
        migrations.AddField(
            model_name='possale',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Net (VAT-extracted) amount. total_amount - subtotal_amount = tax_amount.', max_digits=10),
        ),
        migrations.AddField(
            model_name='possale',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='VAT component included in total_amount.', max_digits=10),
        ),
        migrations.AddField(
            model_name='possale',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='VAT percentage applied at the time of sale, so history never silently changes.', max_digits=5),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='comment',
            field=models.CharField(blank=True, default='', help_text="Cashier note attached to a POS sale line (e.g. 'customer asked for a bag').", max_length=255),
        ),
        migrations.CreateModel(
            name='CashDrawerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=6)),
                ('opened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('opening_float', models.DecimalField(decimal_places=2, default=0, help_text='Cash placed in the drawer at open.', max_digits=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, help_text='Float + net cash movement while open.', max_digits=10)),
                ('counted_cash', models.DecimalField(blank=True, decimal_places=2, help_text='Cash physically counted at close.', max_digits=10, null=True)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, help_text='counted - expected; negative means short.', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawer_sessions_closed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawer_sessions_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Drawer Session',
                'verbose_name_plural': 'Cash Drawer Sessions',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='HeldSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('label', models.CharField(help_text="Short cashier-supplied name, e.g. 'Maria - 2 bags'.", max_length=100)),
                ('payload', models.JSONField(default=dict, help_text='Snapshot of the basket: items, totals, customer id, comments.')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Parked'), ('RESUMED', 'Resumed'), ('DISCARDED', 'Discarded')], db_index=True, default='ACTIVE', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the ticket was resumed or discarded.', null=True)),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_sales', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.customer')),
            ],
            options={
                'verbose_name': 'Held Sale',
                'verbose_name_plural': 'Held Sales',
                'ordering': ['-timestamp'],
            },
        ),
    ]
