# Generated by Django 5.2.11 on 2026-09-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_alter_historicalproduct_image_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HydraulicSow',
        ),
    ]
